# 공통설정

spring.application.name=board

# 활성 프로필 (기본값: dev)
spring.profiles.active=dev

# H2 콘솔 (테스트용, 필요 시 유지)
spring.h2.console.enabled=true

# DevTools 자동 재시작 비활성화
spring.devtools.restart.enabled=false