# 운영 환경

# --- 데이터 소스 ---
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# --- JPA (운영용) ---
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate

# --- 로그 최소화 ---
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=WARN
logging.level.root=INFO

# --- 더미 데이터 실행 안 함 ---
spring.sql.init.mode=never